### ISSUE TITLE
Migrate to Spring Boot 2.0.4

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-server#100]
In 2.0.4 release, the nasty logging issue should be fixed. We will prefer this approach instead of having the logging workaround.

**Comment by romanstrobl** [comment]
We can use these snapshots for testing:
https://repo.spring.io/libs-snapshot/org/springframework/boot/spring-boot-parent/2.0.4.BUILD-SNAPSHOT

**Comment by romanstrobl** [comment]
Migration complete.
