### ISSUE TITLE
Remove ShedlockEntity

### ISSUE THREAD

**Issue by banterCZ** [wultra/powerauth-server#1035]
Remove `ShedlockEntity` and for test purposes add a create schema.

**Comment by jnpsk** [comment]
What else should be done on top of the commit [d407e9e](https://github.com/wultra/powerauth-server/commit/d407e9e658f5bdc50700f785751dd41a95a344ef)?

**Comment by banterCZ** [comment]
> What else should be done on top of the commit [d407e9e](https://github.com/wultra/powerauth-server/commit/d407e9e658f5bdc50700f785751dd41a95a344ef)?

Great! It should be enough. The point is, that the entity is not used in our Java code and has been created only for test purposes, which is handled now by a SQL script.
