### ISSUE TITLE
Add maven-checkstyle-plugin to pom.xml

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-server#109]
We should consider adding maven-checkstyle-plugin to all pom.xml files and handle issues which are discovered by the plug-in. 

For inspiration and sample configuration we can look at Spring boot:
https://github.com/spring-projects/spring-boot/blob/master/pom.xml

**Comment by romanstrobl** [comment]
We should also consider adding spring-javaformat-maven-plugin, if it makes sense for PowerAuth source code.

**Comment by petrdvorak** [comment]
This one can wait for the next release.

**Comment by petrdvorak** [comment]
We do not need this.
