### ISSUE TITLE
Edit callback API documentation

### ISSUE THREAD

**Issue by jnpsk** [wultra/powerauth-server#1097]
There is some missing information in Callback API [documentation](https://developers.wultra.com/components/powerauth-server/1.5.x/documentation/WebServices-Methods)
1. Missing `type` in request body in method `createCallbackUrl`
3. Missing `type` in response in `updateCallbackUrl`.
4. Missing `type` in `GetCallbackUrlListResponse.CallbackUrlList`

**Comment by OliverJanstaWultra** [comment]
Backport to 1.5.x

**Comment by jnpsk** [comment]
Edited and backported to 1.5.x
