### ISSUE TITLE
Move tests from powerauth-tests to this repo

### ISSUE THREAD

**Issue by banterCZ** [wultra/powerauth-server#1099]
Move tests from `powerauth-tests` to this repository. Look at the package `com.wultra.security.powerauth.test.v3x` and search test which do not need cryptography running.

**Comment by jandusil** [comment]
I have identified these tests to move (so far):

```java
testOperationApprove()
testOperationApproveWithValidProximityOtp()
testOperationApproveWithInvalidProximityOtp()
 ```
 
 New added tests:
```java
testOperationCreate()
 ```
