### ISSUE TITLE
Document requirements on OS entropy for deployment of PowerAuth server

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-server#1171]
See:

https://developers.wultra.com/docs/2019.05/powerauth-docker/Special-Configurations#random-number-generator-rng-performance

We need similar documentation for PowerAuth server, ideally including a check of OS entropy and troubleshooting.

**Comment by banterCZ** [comment]
Kernel lower than 5.4: min 256, ideally more than 1024
Kernel 5.4 and higher: min 256 (does not report more anyway)
