### ISSUE TITLE
Modify Paging of Activations

### ISSUE THREAD

**Issue by zcgandcomp** [wultra/powerauth-server#1216]
Modify paging of `POST /action/list` API
- Increase the default size of a page to 500 as 100 is too strict and causes problems in testing
- Introduce sorting for activations 

For the direction and sorting key use `timestamp_created` column and descending order.

Modify API documentation - including dependable projects.

**Comment by banterCZ** [comment]
SQL executed in a test using h2
```sql
select a1_0.activation_id,
       a1_0.activation_code,
       a1_0.activation_name,
       a1_0.activation_otp,
       a1_0.activation_otp_validation,
       a1_0.activation_status,
       a1_0.application_id,
       a1_0.blocked_reason,
       a1_0.counter,
       a1_0.ctr_data,
       a1_0.device_info,
       a1_0.device_public_key_base64,
       a1_0.extras,
       a1_0.failed_attempts,
       a1_0.flags,
       a1_0.master_keypair_id,
       a1_0.max_failed_attempts,
       a1_0.platform,
       a1_0.server_private_key_base64,
       a1_0.server_private_key_encryption,
       a1_0.server_public_key_base64,
       a1_0.timestamp_activation_expire,
       a1_0.timestamp_created,
       a1_0.timestamp_last_change,
       a1_0.timestamp_last_used,
       a1_0.user_id,
       a1_0.version
from pa_activation a1_0
where a1_0.user_id=?
order by a1_0.timestamp_created desc
offset ? rows fetch first ? rows only
```

**Comment by kopovan** [comment]
POST /action/list -> **POST /activation/list**

**Comment by kopovan** [comment]
Summary of the implementation:
https://mtoken-demo.wultra.app/powerauth-cloud/swagger-ui/index.html#/Registrations/getRegistrationList

https://powerauth-dev.westeurope.cloudapp.azure.com/powerauth-java-server/swagger-ui/index.html#/PowerAuth%20Controller%20V3/getActivationListForUser
1. For [PAC](https://mtoken-demo.wultra.app/powerauth-cloud/swagger-ui/index.html#/Registrations/getRegistrationList
) there is a switch parameter "removed", which includes following options: true, false, not specified --. The behaviour should be as following:
removed=true - retrieves all registrations (1 - CREATED, 2 - PENDING_COMMIT, 3 - ACTIVE, 4 - BLOCKED, 5 - REMOVED)
removed=false - retrieves only active and blocked registrations
removed by default (not specified --) - retrieves only active a blocked
<img src="https://github.com/wultra/powerauth-server/assets/135111051/a7f11a88-6c02-4def-93f3-4aa6f79c747a" width="300" />

For [PAS](https://powerauth-dev.westeurope.cloudapp.azure.com/powerauth-java-server/swagger-ui/index.html#/PowerAuth%20Controller%20V3/getActivationListForUser
) we have optional parameter "activationStatuses", it will filter registrations based on the specified criteria. If not entered it returns all.
<img src="https://github.com/wultra/powerauth-server/assets/135111051/5ec50bb3-a145-407d-ac08-6bf9889ec9a4" width="300" />

2. in the database table `pa_activation` - `select user_id, count(1) from pa_activation group by user_id having count(1)>100 order by count(1) desc` you can see how many registrations all the users have. 
3. applicationId must be valid for the registration to appear in the list
4. by default 500 registrations should be retreived
5. PAC - when there is more than 2000 registrations it does not return internal server error anymore -> was not tested
6. The registrations are sorted by `timestamp_created` in descending order
