### ISSUE TITLE
Filtering of operations in operation list by activation ID and flags

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-server#1224]
Allow filtering of operations in activation list endpoint by:
- `activation ID` - for scoping of an operation to a specific user device
- `activation flag` - for scoping of user devices to a specific activation flag which is set for the operation when it is created

The `operationList` and `operationPendingList` endpoints should filter operations returned in the list using new optional parameter `activationId`.

Parameters used when obtaining the list of operations (pending / all):
- `userId`
- `applications`
- `activationId` (optional)

The existing `activationFlag` parameter should be either removed or deprecated, because it is not used.

Operations for specific user and application are found. Following filters are applied:
- It is checked whether the operation is scoped to an `activationId`, if so, only operations that match the `activationId` sent in the request are returned.
- It is checked whether the operation is scoped to an activation flag, if so, the flags that this activation has are checked according to the `activationId` and only those operations are returned where the `activationFlag` from the operation is included in the activation flags.
- Otherwise, the `activationId` sent in the request will not be used, although it would probably be nice to log it in some debug.

Both of these filters are applied.

After applying the filters, paging is applied, the order is important.

**Comment by zcgandcomp** [comment]
in the list of operation of the `userId`, we should not see operations created for different `activationId` (i.e. the `activationId` in the operation is specified)
Also if the activation is flagged and the operation is created with a flag the list should return only operations with the flag of the device.

**Comment by jandusil** [comment]
@kopovan Target endpoints: 
`/rest/v3/operation/list`
`/rest/v3/operation/list/pending`

When calling these endpoints with `activationId` in the request object we should not see  operations created for different `activationId`. We may see some activations specified for a `userId ` that are not scoped for any `activationId` (i. e. `activationId` is null or not present).

Moreover, test that, if the `activationId` is present in the request, the returned operations should all be either without any `activationFlag` or their `activationFlag` should  be present on the list of flags scoped to the `activationId`. You can see the flags scoped for `activationId ` by calling endpoint `/rest/v3/activation/flags/list`.
