### ISSUE TITLE
Personalized FIDO2 assertion challenge

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-server#1374]
Currently, we allow fetching an anonymous assertion challenge. We should allow personalizing the challenge immediately. As a result, we can return list of supported FIDO2 authenticators right away and ensure future check of the authenticator that was actually used against allowed authenticators.

**Comment by zcgandcomp** [comment]
TBD:
Goal - normalize the API, adopt to the fact that Wultra Hardware Authentication is currently not supporting discoverable credentials.

The recommended flow is:
The server creates an assertion challenge for userId supplied by a customer server.
The server will return a list of relevant `credentialId` - these are sent by a customer server to the authenticator.
The customer server authenticates the challenge.
The server asserts a scope of the challenge if the operation is scoped - either to userId or `activationId`

Required changes:
- add `userId` and `activationId` to `AssertionChallengeRequest` to enable scoping of the challenge to the user or the specific authenticator
- the requestAssertionChallenge method has to return a list of `credentialId` as a result
- fix logic for `externalId` in AssertionChallengeRequest - it is currently in the API but is not used in the operation creation.
- Fix `attemptApproveOperation` logic - if the operation is scoped.
