### ISSUE TITLE
Allow fetching assertion challenge related to existing operation

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-server#1375]
Currently, combining multiple means of authentication on the web could result in multiple operations being created. We should allow requesting FIDO2 assertion challenge with the provided operation ID, so as to avoid this duplicity.

**Comment by banterCZ** [comment]
Add optional `operationId` to `POST /fido2/assertions/challenge`. If filled, we load the operation instead of creating a new one.

**Comment by kopovan** [comment]
I work with the table `SELECT * FROM public.pa_operation ORDER BY timestamp_created DESC`. I retrieve the ID and call the endpoint with operationId — no new record is created in the table. I call the endpoint without operationId — a new record is created in the table.
![image](https://github.com/user-attachments/assets/1e24e98a-b9b4-4378-9aca-d474cd6cd159)
![image](https://github.com/user-attachments/assets/39889281-3390-4f23-951d-b1a174884c20)
