### ISSUE TITLE
FIDO2: externalize authenticator configuration

### ISSUE THREAD

**Issue by zcgandcomp** [wultra/powerauth-server#1393]
Currently, Fido2Authenticators.java contains a hardcoded configuration for the FIDO authenticator.

Externalize the config so it can be changed by configuration. Suggestion DB - but be aware of the performance consequences.

The configuration changes are not expected to be often - in production for the first release and more frequent for setting in the test environments. So singleton with long eviction should be fine.

**Comment by jnpsk** [comment]
Spring has a [caching mechanism](https://www.baeldung.com/spring-cache-tutorial). Basically it is a group of method level annotations that are able to cache method's return value identified by method's input argument. One of the possible cache implementation is `ConcurrentHashMap`. So we can implement standard database repository and then annotate its methods as cachable to speed up repeated requests.

**Comment by romanstrobl** [comment]
Can we add the new table? https://github.com/wultra/powerauth-server/blob/issues/1393-external-authenticator-config/docs/Database-Structure.md
