### ISSUE TITLE
Validate activation ID when creating operation

### ISSUE THREAD

**Issue by zcgandcomp** [wultra/powerauth-server#1399]
Originally reported as a problem when claiming non-personalized operation. It is possible to specify a user ID different from the activation one.

The root cause is already in the operation creation. It has to be validated that if the activation ID is specified, the user ID is also specified and matches the value in the activation (avoid usage of the activation of a different user).

This issue does not affect security, just only data consistency.

**Comment by banterCZ** [comment]
Related to #852

**Comment by zcgandcomp** [comment]
Waiting for testing by @kopovan

**Comment by banterCZ** [comment]
Mind that the behavior has been changed in #1552

**Comment by kopovan** [comment]
@zcgandcomp please review the test results below as the expected result is not 100% clear to me from the description. 

Positive case
1. `userId` and `registrationId` are both present in the request body - operation created, both parameters are present in the response
2. `userId` only - operation created, `userId` is present in the response
3. `registrationId` only - operation created, both parameters are present in the response

Negative
1. non existing `registrationId` - error `No active registration found matching operation criteria`
2. non existing `userId` - error `No active registration found matching operation criteria`
3. existing `userId` and `registrationId` but not compatible - error `No active registration found matching operation criteria`
