### ISSUE TITLE
Investigate @Scheduled methods with @Transactional annotation

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-server#1472]
We should review the behavior of the combination of scheduling and transactional behavior, just to be sure there could be no strange side effects.

**Comment by banterCZ** [comment]
See
- https://stackoverflow.com/questions/18399006/spring-transactional-scheduled-method-throws-transactionexception
- https://stackoverflow.com/questions/45355601/why-scheduled-annotation-doesnt-work-with-transaction-annotation-spring-boot
