### ISSUE TITLE
Optimization: Operation expiration optimization

### ISSUE THREAD

**Issue by zcgandcomp** [wultra/powerauth-server#1482]
The PowerAuth Server expires operation based on the attribute `timestampExpires`.
When a large number of operations is created the expiration can take very long time (days)
When selecting expired operations by status and `timestampExpires`. Index `pa_operation_status_exp` is used. However, the usage of the index provides worse performance.

Optimize the task:

- Limit the number of expired operations (e.g., 100) to prevent long-running sessions and unplanned resource exhaustion on the server.
- Drop unused index - check if the field is not used for selection somewhere else - in this case we cannot drop it.

**Comment by jnpsk** [comment]
I have new observations regarding this issue:

1. The `pa_operation_status_exp` index is used if its columns are swapped in the index definition: `CREATE INDEX pa_operation_status_exp ON pa_operation(status, timestamp_expires);`, i.e. range is in the second place.
2. The bottleneck does not seem to be the stream of operations to be expired, instead the significant amount of time is spent on `CallbackUrlBehavior#notifyCallbackListenersOnOperationChange`, which is called for each operation to be set EXPIRED. So instead I investigated the callback repository calls further and this issue will optimize the method mentioned.
