### ISSUE TITLE
Data escaping in operation template

### ISSUE THREAD

**Issue by kopovan** [wultra/powerauth-server#1523]
In the demo app when I enter into any field following character * it will simply cut off the rest of the value

f.e. I send 55464*5464!@#$% -> but on the token only this is displayed 55464

**Comment by hvge** [comment]
Let me add a more context to this bug report. It seems that PowerAuth Server doesn't perform escaping of some special characters according to our [operation data format specification](https://developers.wultra.com/components/powerauth-webflow/1.7.x/documentation/Operation-Data#data-types) (see `{TEXT}` data type) when an operation is being created. This may lead to the broken operation data if non-escaped character is provided as the parameter to the operation data template.

The question is, do we have to fix this? If the responsibility of the escaping is in client's hands (e.g. text must be already escaped, when passed to PAS), then we should at least update the documentation. 

What @kopovan is referencing is that our own FIDO2 demo application has this wrongly implemented, leading to broken data displayed in the HW token.

**Comment by banterCZ** [comment]
When deployed, it PAS should start escaping now.

**Comment by kopovan** [comment]
retest ok
<img src="https://github.com/user-attachments/assets/0ec46196-fc20-47cc-b7d1-90cd3607ac9f" width="300" />
