### ISSUE TITLE
Callback OAUTH2.x authorization

### ISSUE THREAD

**Issue by zcgandcomp** [wultra/powerauth-server#1533]
Add capability to protect callbacks via OAUTH2.x. 

Support grant_type`client_credentials`.

Encrypt the authentication column with the general encryption key.

Derive the specific key (e.g. from application id).

Update the API to support the OAUTH authorizaton as the API will be only option how to setup callbacks correctly (with authentication).

Attributes, if the authentication column is encrypted, are required; otherwise, we will face migration issues.

**Comment by OliverJanstaWultra** [comment]
Peter approves.

**Comment by banterCZ** [comment]
@kopovan We should test the following:
- PAS REST API
- Admin GUI
- Callback authentication (required infrastructure setup by @korbelm)

**Comment by OliverJanstaWultra** [comment]
Deploy on SMOKE and STABLE

**Comment by korbelm** [comment]
Looks like oauth auth on callbacks works fine
