### ISSUE TITLE
DB migration issue (MS SQL, possible Oracle)

### ISSUE THREAD

**Issue by zcgandcomp** [wultra/powerauth-server#1538]
Step to reproduce
Install version prior to 1.7.x
Create activation
Migrate to 1.7.x

Expected behavior:
The record in the table `pa_activation` has "powerauth" in the column `protocol`.

Actual behavior:
The record in the table `pa_activation` has an empty column `protocol` on MS SQL. 

The null value leads to:

```
Runtime exception or error occurred, transaction will be rolled back

java.lang.NullPointerException: Cannot invoke "java.lang.String.toUpperCase()" because the return value of "io.getlime.security.powerauth.app.server.database.model.entity.ActivationRecordEntity.getProtocol()" is null
```
when calling API
`GET {{powerauth_url}}/v2/registrations?userId={user_id}`

**Comment by banterCZ** [comment]
See
- https://github.com/liquibase/liquibase/issues/3417
- https://github.com/liquibase/liquibase/issues/4644
