### ISSUE TITLE
Enable to lookup the userId if operation is created with activationId but without userId.

### ISSUE THREAD

**Issue by zcgandcomp** [wultra/powerauth-server#1552]
If `userId` is not present, but the operation is created with `activationId`, use the `userId` of the activation for the operation creation.

**Comment by banterCZ** [comment]
Changes behavior introduced in #1399

**Comment by banterCZ** [comment]
Merged, ready to test but not deployed yet. See also #1399

**Comment by kopovan** [comment]
test ok, see comment https://github.com/wultra/powerauth-server/issues/1399#issuecomment-2233647827
