### ISSUE TITLE
OIDC: Implement per-record encryption in configuration table

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-server#1588]
For activation using OIDC, we need to be able to encrypt the OIDC configuration using per-record encryption, due to storage of `client_secret` value required for accessing OAuth 2.0 tokens.

**Comment by banterCZ** [comment]
🤔 There is `ListToJsonConverter` for `values` column, but JPA is not able to take two columns into the account, see https://stackoverflow.com/questions/25172083/creating-converters-based-on-multiple-attributes-in-jpa-2-1

**Comment by banterCZ** [comment]
Hibernate listeners look overcomplicated https://arnoldgalovics.com/jpa-entity-encryption/
