### ISSUE TITLE
Add commit phase to allow activation commit on key exchange

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-server#1670]
Add a `commitPhase` parameter into `InitActivationRequest` to allow commit on key exchange or in `PENDING_COMMIT` state (default). Deprecate the original `activationOtpValidation` parameter, whose value can be determined from request data. Keep compatibility for existing scenarios with OTP.

**Comment by kopovan** [comment]
tested on Stable https://github.com/wultra/tasklist/issues/373#issuecomment-2388285952
