### ISSUE TITLE
Remove cryptography operations from transactions where possible

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-server#217]
Currently we mark all PowerAuth service methods with `@Transactional` annotation to make sure transactions are used for all database operations. Some of the cryptography operations (encryption/decryption, key generation, key derivation, key conversion, etc.) do not require to run inside database transactions. It should be possible to move some of the crypto operations before or after database transactions and mark only database-related parts of code as `@Transactional`.

This change should bring many benefits:
- Shorter transaction time will improve database performance.
- The chances of database deadlocks should decrease greatly because of lower number of parallel transactions. This should especially help databases sensitive to deadlocks (e.g. MSSQL).
- Improved response time for web service calls which use the database.
- Less time spent in waiting for activation locks.

**Comment by petrdvorak** [comment]
This no longer causes issues and hopefully, we can safely close.
