### ISSUE TITLE
Creating the Database Schema not working for PostgreSQL

### ISSUE THREAD

**Issue by martinpapez** [wultra/powerauth-server#343]
When I downloaded sql script `create_schema.sql` from link https://developers.wultra.com/docs/2019.05/powerauth-server/sql/postgresql/create_schema.sql and tried to import it to db it doesn't work. Could you please fix the script for PostgreSQL?

PostgreSQL 11.4 on AWS RDS

Logs from import:
```shell
/ # psql --host=<DB-HOST> --username=powerauth --db=powerauth < create_schema.sql 
Password for user powerauth: 
CREATE SEQUENCE
CREATE SEQUENCE
CREATE SEQUENCE
CREATE SEQUENCE
CREATE SEQUENCE
CREATE SEQUENCE
CREATE SEQUENCE
CREATE SEQUENCE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
CREATE TABLE
ERROR:  type "number" does not exist
LINE 2:     "id"                            NUMBER(19,0) NOT NULL PR...
                                            ^
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ALTER TABLE
ERROR:  relation "pa_recovery_config" does not exist
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
ERROR:  relation "pa_recovery_code" already exists
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
```

**Comment by petrdvorak** [comment]
This issue happened by incorrectly converting the Oracle SQL script. I have fixed this in PR already waiting for the merge (along with some other minor fixes, such as using BIGINT for tables with quickly growing record numbers). In the meanwhile, you can use the following file:

https://github.com/wultra/powerauth-server/blob/014f11f8cc8a20e019177f5445dbda57f140670d/docs/sql/postgresql/create_schema.sql

**Comment by martinpapez** [comment]
Thank you very much. It works now.
