### ISSUE TITLE
Allow vault key unlock with biometry

### ISSUE THREAD

**Issue by hvge** [wultra/powerauth-server#363]
Starting with the server version `0.22`, it is no longer possible to acquire a vault unlock key with the biometric authentication (possession + biometry). Due to a compatibility reasons, we have to put this feature back, but configurable and disabled by default. 

This change should be implemented as hotfix to `releases/0.22.x` and merged to `develop`.

**Comment by romanstrobl** [comment]
Issue still needs to be merged into develop branch.
