### ISSUE TITLE
Add a column for the original activation version

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-server#501]
Currently, activation only stores the current version. We should:

- audit the activation version in table `pa_activation_history`
  - add a new `version` column which stores the current activation version and is specified whenever an activation history event is audited
  - add a new `AdditionalInformation` constant `ACTIVATION_VERSION_CHANGED` for activation history audit, use it:
    - during activation prepare (`null` version -> specific version)
    - during upgrade commit (version changes to a newer one)
  - for other activation changes the current activation version is stored, it is retrieved from activation entity

**Comment by romanstrobl** [comment]
The issue will have to wait for the next release.

**Comment by banterCZ** [comment]
Expected _level of done_: Create activation 2.1 and upgrade to 3.1, the new version should be recorded in the history.
