### ISSUE TITLE
Explore use of Lombok to get rid of getters and setters

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-server#526]
To make the entity, DAO, and DTO classes more readable, we should look at Lombok to see if we can get rid of getters and setters.

https://projectlombok.org/

**Comment by romanstrobl** [comment]
Is there a reason why not use _records_, the standard solution for getting rid of getters and setters in Java 14? See: https://www.baeldung.com/java-record-keyword

I am not a fan of adding the Lombok library for this purpose, when a standardized solution is available. Although Lombok is quite cool, I've had a bad experience with debugging the generated code by Lombok.

**Comment by petrdvorak** [comment]
Let's have a look at "records" too, I just wonder if Java 14 is not too soon for our customers...

**Comment by romanstrobl** [comment]
I have reserarched whether we could use source level 14 and binary target 8. It is possible, but it requires some tricks, e.g.: https://github.com/bsideup/jabel. Since there is no simple solution for records on Java binary target 8, I think we should use Lombok.

**Comment by romanstrobl** [comment]
I believe this issue has low priority because it is a replacement for existing model definitions. We can implement this change in the next release.

**Comment by petrdvorak** [comment]
Not required anymore.
