### ISSUE TITLE
Write RESTful API model manually

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-server#532]
Since we are deprecating SOAP and prioritizing REST, I think we should write the model classes manually in the "model" project. The XSD we have becomes hard to manage, and we do not want to invest our energy into fixing it.

At the same time, we should probably finally break the REST controller down into several smaller controller classes, as well as evaluate the need for the `*ServiceImpl` classes.

**Comment by romanstrobl** [comment]
Note that this change will also require removing the SOAP clients which are either generated from XSD or use WSDL.

**Comment by petrdvorak** [comment]
@romanstrobl I think that we simply should not mix SOAP and REST approaches anymore, since REST changed from "backup" to "primary". For some time, we might need to duplicate work in the XSD file for the SOAP clients, but I already hit a limit of SOAP when I needed to send a request with simple `Map<String, String>` which would require painful equilibristics in XSD.

**Comment by romanstrobl** [comment]
Ok. Right now by reusing the same model classes between REST and SOAP we can switch tests between SOAP and REST easily (one config parameter change). Once we start diverging the model classes we will also need to branch the tests or eventually stop testing SOAP.

**Comment by petrdvorak** [comment]
Fixed with the removal of the SOAP interface.
