### ISSUE TITLE
Prepare a more generic auditing table

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-server#548]
Currently, we are auditing signatures. However, this may not be the best granularity since we may need to have a better audit trail across all events that occur in the system. As such, we should prepare generic auditing support, probably by integrating some well-known technologies, such as Elastic.

**Comment by romanstrobl** [comment]
I opened an issue to implement shared logic for auditing:
https://github.com/wultra/lime-java-core/issues/34

**Comment by romanstrobl** [comment]
The issue will have to wait for the next release.

**Comment by petrdvorak** [comment]
Let's include also comments from #511 (closed as duplicate)
