### ISSUE TITLE
Equals and hashCode for PowerAuthClient Request and Response Classes

### ISSUE THREAD

**Issue by banterCZ** [wultra/powerauth-server#631]
I suggest to add `equals` and `hashCode` methods for PowerAuthClient request/response classes such as `com.wultra.security.powerauth.client.v3.GetActivationListForUserRequest`.

When I mock PowerAuthClient I have to use (for example) `org.mockito.internal.matchers.apachecommons.ReflectionEquals`.

**Comment by petrdvorak** [comment]
These classes are now handled via Lombok and contain equals and hashCode.
