### ISSUE TITLE
toString for PowerAuthClient Request and Response Classes

### ISSUE THREAD

**Issue by banterCZ** [wultra/powerauth-server#632]
I suggest to add `toString` method for PowerAuthClient request/response classes such as `com.wultra.security.powerauth.client.v3.GetActivationListForUserRequest`.

I understand that some information are sensitive and should be hidden. For example, you may extend `org.apache.commons.lang3.builder.ToStringBuilder` and implement custom `SensitiveToStringBuilder` with `appendSesitive` method to mask values like `*****`. Of course, it is a question of transitive dependency.

**Comment by petrdvorak** [comment]
These classes are now handled with Lombok and contain toString method.
