### ISSUE TITLE
Do not log ACTIVATION_VERSION_CHANGED when preparing the activation

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-server#689]
Currently, we incorrectly log activation status change reason whenever the activation goes to PENDING_COMMIT:

<img width="784" alt="Screenshot 2022-05-09 at 14 53 16" src="https://user-images.githubusercontent.com/516597/167414066-d639e981-bfe2-4b82-b75d-adea2a730aec.png">

https://github.com/wultra/powerauth-server/blame/32df0accfe80f46581ea9936cd818747157c5dea/powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/v3/ActivationServiceBehavior.java#L948

**Comment by banterCZ** [comment]
Relates to #501
