### ISSUE TITLE
Found use of deprecated org.hibernate.id.SequenceGenerator

### ISSUE THREAD

**Issue by banterCZ** [wultra/powerauth-server#704]
A warning in a log is seen

> org.hibernate.orm.deprecation            : HHH90000014: Found use of deprecated [org.hibernate.id.SequenceGenerator] sequence-based id generator; use org.hibernate.id.enhanced.SequenceStyleGenerator instead.  See Hibernate Domain Model Mapping Guide for details.

Try to use `properties.put("hibernate.id.new_generator_mappings", "true");`

https://vladmihalcea.com/from-jpa-to-hibernates-legacy-and-enhanced-identifier-generators/
https://stackoverflow.com/questions/39861098/replace-sequencegenerator-since-its-deprecated

**Comment by petrdvorak** [comment]
Note that this issue may impact existing deployments with already IDs via original sequence generators. Make sure to include the proper migration guides. We already discussed this in #136 - make sure to search for issues before reporting new ones.

**Comment by banterCZ** [comment]
After upgrading to Spring Boot 3 and Hibernate 6.2 `org.hibernate.id.SequenceGenerator` is not present anymore.
