### ISSUE TITLE
Failed to create application version from Admin

### ISSUE THREAD

**Issue by hvge** [wultra/powerauth-server#715]
PowerAuth Admin is unable to create a new application version. It seems that there's a missing parameter `applicationVersionId` in the request. The parameter is required since we moved to string based application ids.

The following exception is reported:
```
org.springframework.web.bind.MissingServletRequestParameterException: Required request parameter 'applicationVersionId' for method parameter type String is not present
```

**Comment by banterCZ** [comment]
Affected url `/powerauth-admin/application/detail/{id}/version/create/do.submit`
