### ISSUE TITLE
Duplicate application versions in database

### ISSUE THREAD

**Issue by hvge** [wultra/powerauth-server#717]
Currently, our dev environment has a lot of duplicates of application versions (see application `AutomaticTest-IOS`). This happened due to my bug in iOS integration tests, where the required application version was created event if it existed. So, once we migrated to the string based application ids, we failed to properly migrate the data from the old database.

The result is that API calls that manage support / un-support of application versions fails on exception, because the database return more than one result.

I think the problem has two layers:

- First, I think the duplicates should not be allowed, so the `applicationVersionId` should be unique key now.
- Second, we have to create a proper migration guidelines.

I did not test duplicates in applications, perhaps it's the same situation.

**Comment by petrdvorak** [comment]
Note that the `applicationVersionId` should be unique for given application. In applications, we currently handle it both on index and in application code. The migration script can be simple note in the guidelines. Luckilly, not many customers use versioning...
