### ISSUE TITLE
Add UI hints to the operation template and operation

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-server#761]
Currently, we handle UI extensions in the Enrollment Server. However, this does not cover offline operations. As a result, we should also ensure that PAS operations contain these UI hints. The enrollment Server can still override them with their own value if needed, so we can keep the enhancements made on the enrollment server.

**Comment by banterCZ** [comment]
Already done as Risk Flags at PAS #775 and UI at enrollment-server https://github.com/wultra/enrollment-server/issues/306

**Comment by banterCZ** [comment]
Already done as Risk Flags at PAS #775 and UI at enrollment-server https://github.com/wultra/enrollment-server/issues/306
