### ISSUE TITLE
Expiration of activations

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-server#80]
We should introduce expiration for activations. The expiration time should be configurable. We should also consider whether expiration should be tied to the number of signature verifications. We also need to implement a workflow for reactivation - the user needs to be informed about expired activation and a new activation work flow should be initiated.

It seems it is better not to force this setting and allow clients to migrate to enabled expiration at their own pace because it may have impact on the client application which enables activation (e.g. internet banking).

The reason for expiration of activations is increasing resistance against brute force attacks, and should remain optional only for clients who want such extra level of security.

**Comment by petrdvorak** [comment]
Closed thanks to incorrect commit message.

**Comment by petrdvorak** [comment]
Probably not required.
