### ISSUE TITLE
Allow scoping operation to a single activation ID

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-server#852]
To improve use cases on mobile, it would be nice to allow specifying an operation ID for a particular mobile device defined by activation ID. As a result, the developers could:

- Create a new operation on a specific mobile device (activation ID).
- Approve the operation just on that specific mobile device (activation ID).

**Comment by OliverJanstaWultra** [comment]
Please analyze - @romanstrobl

**Comment by OliverJanstaWultra** [comment]
@jandusil will let @kopovan know about how to test it.

**Comment by kopovan** [comment]
Waiting for a fix: https://github.com/wultra/powerauth-cloud/issues/397#issuecomment-1853596066

**Comment by kopovan** [comment]
test ok, see more in the comment: https://github.com/wultra/powerauth-server/issues/1224#issuecomment-1878769837
