### ISSUE TITLE
Invalid JPA lock timeout setting

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-server#881]
The following setting is incorrect:

```properties
# Database Lock Timeout Configuration
spring.jpa.properties.lock.timeout=10000
```

The correct configuration is:
```properties
# Database Lock Timeout Configuration
spring.jpa.properties.javax.persistence.lock.timeout=10000
```

**Comment by banterCZ** [comment]
It is `spring.jpa.properties.javax.persistence.lock.timeout` for Spring Boot 2.7 but `spring.jpa.properties.jakarta.persistence.lock.timeout` since Spring Boot 3.
