### ISSUE TITLE
Evaluate if using Duration works for configuration properties

### ISSUE THREAD

**Issue by petrdvorak** [wultra/powerauth-server#968]
In #953, we changed the millisecond representation to Duration. We should investigate if this retains at least the millisecond precision.

**Comment by jandusil** [comment]
Some reading:

- [https://www.baeldung.com/configuration-properties-in-spring-boot](https://www.baeldung.com/configuration-properties-in-spring-boot)

**Comment by banterCZ** [comment]
`Duration` keeps milliseconds precision, proved by an example:

```java
Duration x = Duration.parse("PT2M");
System.out.println(x.toMillis()); // 120000

Duration y = Duration.parse("PT20.345S");
System.out.println(y.toMillis()); // 20345
```
