### ISSUE TITLE
Add column for signature metadata

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-server#971]
PowerAuth server should support mutliple signature types, hence columns `signature_data_method` and `signature_data_uri_id` in table `pa_signature_audit` should be generified into a single JSON column e.g. `signature_metadata`.

Sample structure of contents of column `signature_metadata` after migration to JSON format:
```json
{
    "signature_data_method": "POST",
    "signature_data_uri_id": "/authorize"
}
```

Other signature types will use dedicated JSONs. Let's prepare classes which model various signature types, for this release only the PowerAuth signature model class type.

**Comment by banterCZ** [comment]
A follow-up to #500
