### ISSUE TITLE
Remove migration to java.time.Duration from migration guide

### ISSUE THREAD

**Issue by romanstrobl** [wultra/powerauth-server#999]
The migration to `java.time.Duration` is not necessary for this release.

See: https://github.com/wultra/powerauth-server/blob/bd40dcf394b2fdaf2042de8ac30c5da9885d2445/docs/PowerAuth-Server-1.5.0.md#configuration-properties

**Comment by banterCZ** [comment]
Regression to #978 reintroduces by wrong solving of merge conflict at #965
